# Generated by Django 4.2.4 on 2023-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=110)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('quries', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
